notifications:
  commits: commits@security.apache.org
  issues: commits@security.apache.org
  jobs: commits@security.apache.org
  pullrequests: commits@security.apache.org
  discussions: commits@security.apache.org

staging:
  profile:

publish:
  whoami: asf-site

github:
  description: "Website sources for the Apache Security website"
  homepage: https://security.apache.org
  labels:
    - apache
    - security
    - hugo
    - website
  features:
    issues: true
  pull_requests:
    del_branch_on_merge: true
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
